package com.example.todoapp.data.todo

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Defines the structure of the 'todos_table' in the database as an entity.
 *
 * This data class represents a single item, with properties that correspond to columns in the
 * 'todos_table'. Room uses this class to create the table and instantiate objects from rows in the database.
 *
 * @property id Unique identifier for the item. It is autogenerated by the Room database.
 * @property title The title or description of the item.
 * @property completed Indicates whether the item has been completed.
 * @property completedAt The timestamp when the item was marked as completed, null if not completed.
 */
@Entity(tableName = "todos_table")
data class ToDo(
    @PrimaryKey(autoGenerate = true) var id: Long = 0L,
    var title: String = "",
    var completed: Boolean = false,
    var completedAt: Long? = null
)